language: php

php:
  - 5.3
  - 5.4

services: mongodb

before_script:
  - composer install --dev

script: phpunit --coverage-text -c tests/

notifications:
  email:
    - gediminas.morkevicius@gmail.com
