language: php

php:
  - 5.3
  - 5.4
  - 5.5

services: mongodb

before_install:
  - sh -c "if [[ $TRAVIS_PHP_VERSION != 'hhvm' && `php-config --vernum` -ge 50500 ]]; then yes ''| pecl install apcu-beta; else echo 'extension="apc.so"' >> ./tests/travis/php.ini; fi"
  - sh -c "if [ $TRAVIS_PHP_VERSION != 'hhvm' ]; then phpenv config-add ./tests/travis/php.ini; fi"

install:
  - composer install --dev

script: phpunit -c tests/

notifications:
  email:
    - gediminas.morkevicius@gmail.com
    - developers@atlantic18.com
